"""Initial revision

Revision ID: 5c09ed86625b
Revises: 
Create Date: 2026-04-29 15:43:09.672319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c09ed86625b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('time_per_question', sa.Integer(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('quiz_name', sa.String(length=100), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.String(), nullable=True),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('results')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
