"""add image fields to quizzes and questions

Revision ID: dcb0dca56512
Revises: f1d16e27cf69
Create Date: 2026-06-04 15:35:04.691510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb0dca56512'
down_revision: Union[str, Sequence[str], None] = 'f1d16e27cf69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('image', sa.String(length=500), nullable=True))
    op.add_column('quizzes', sa.Column('cover_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'cover_image')
    op.drop_column('questions', 'image')
    # ### end Alembic commands ###
