"""5th revision

Revision ID: e35164e87d1a
Revises: e5a2b1af9363
Create Date: 2026-05-15 17:28:58.721863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35164e87d1a'
down_revision: Union[str, Sequence[str], None] = 'e5a2b1af9363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'emoji')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
