"""fourth revision

Revision ID: e5a2b1af9363
Revises: fdc39e6d569a
Create Date: 2026-05-14 16:31:01.699670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a2b1af9363'
down_revision: Union[str, Sequence[str], None] = 'fdc39e6d569a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_answers', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_answers', 'response_time_ms')
    # ### end Alembic commands ###
