"""6th revision

Revision ID: f1d16e27cf69
Revises: e35164e87d1a
Create Date: 2026-05-19 16:44:21.490890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d16e27cf69'
down_revision: Union[str, Sequence[str], None] = 'e35164e87d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'emoji')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
