"""third revision

Revision ID: fdc39e6d569a
Revises: 81a46d9af1fa
Create Date: 2026-05-10 20:29:23.453300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc39e6d569a'
down_revision: Union[str, Sequence[str], None] = '81a46d9af1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'quiz_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
